### ISSUE TITLE
#146 - product user 관련 로직 도입

### ISSUE THREAD

**Issue by shin-jisong** [Start-as-Web-Developers/tumblbug-clone-coding#146]
## Tasks
- [x] product dto 수정
- [x] product 컨트롤러 수정
- [x] product 서비스 수정

## Related Issues
- #143 

## Time line
06.01 ~ 06.07
