### ISSUE TITLE
#147 - component user 관련 로직 도입

### ISSUE THREAD

**Issue by shin-jisong** [Start-as-Web-Developers/tumblbug-clone-coding#147]
## Tasks
- [x] component dto 생성
- [x] component 컨트롤러 수정
- [x] component 서비스 수정

## Related Issues
- #146 

## Time line
06.01 ~ 06.07
