### ISSUE TITLE
#52 - 프로젝트 업로드 페이지 관련 컴포넌트 리팩토링

### ISSUE THREAD

**Issue by Moon-GD** [Start-as-Web-Developers/tumblbug-clone-coding#52]
## Tasks
- [x] CardAddModal.tsx 리팩토링
- [x] CategorySelectModal.tsx 리팩토링
- [x] ProjectRegisterColumn.tsx 리팩토링

## Related Issues
- #48 프로젝트 업로드 뷰 제작
- #49 프로젝트 업로드 페이지 이벤트 연동

## Time line
04.29 ~ 04.30

**Comment by Moon-GD** [comment]
tsx 파일 위주로 리팩토링 완료하였습니다.
함수형 컴포넌트가 아닌 일반 함수는 화살표 함수로 통일하였습니다.
