### ISSUE TITLE
#54 - 프로젝트 업로드 폴더 테스트 코드 작성

### ISSUE THREAD

**Issue by Moon-GD** [Start-as-Web-Developers/tumblbug-clone-coding#54]
## Tasks
- [x] CardAddModal.tsx 테스트 코드 작성
- [x] CategorySelectModal.tsx 테스트 코드 작성
- [x] ProjectRegisterColumn.tsx 테스트 코드 작

## Related Issues
- #48 - 프로젝트 업로드 뷰 제작
- #52 프로젝트 업로드 페이지 관련 컴포넌트 리팩토링

## Time line
04.29 ~ 04.30

**Comment by Moon-GD** [comment]
혼자서 작성 가능한 테스트 코드 작성 완료하였습니다.

<img width="763" alt="project upload testing" src="https://user-images.githubusercontent.com/74173976/235458553-e44e8643-7b09-4e0d-8de9-931482faf2a6.png">
- ProjectUpload 폴더 테스트 코드 작성 (그룹 : 11개, test 18개)
    - CardAddModal.tsx 테스트 코드 작성 (그룹 : 6개, test 10개)
    - CategorySelectionModal.tsx 테스트 코드 작성 (그룹 : 1개, test 1개)
    - ProjectRegisterColumn.tsx 테스트 코드 작성 (그룹 : 4개, test 7개)
