### ISSUE TITLE
#68 - 좋아요 기능 관련 API 작성 및 프로젝트 구현

### ISSUE THREAD

**Issue by zangsu** [Start-as-Web-Developers/tumblbug-clone-coding#68]
## Tasks
- [x] API 명세서 작성
- [x] `LikeRepository`와 `LikeController` 생성
- [x] 좋아요 기능과 관련된 비즈니스 로직 작성

## Related Issues
- #34 
- #46 

## Time line
05.18 ~ 05.20
