### ISSUE TITLE
#72 - component API 구현

### ISSUE THREAD

**Issue by shin-jisong** [Start-as-Web-Developers/tumblbug-clone-coding#72]
## Tasks
- [x] component crud API
- [x] component controller 작성
- [x]  component repository 수정

## Related Issues
- #69 

## Time line
05.04 - 05.10

**Additional context**
project 수정 시 필요한 component API를 새로 설계하였고 이를 구현 예정입니다.
