### ISSUE TITLE
#8 - AWS EC2에 서버 환경 구축

### ISSUE THREAD

**Issue by shin-jisong** [Start-as-Web-Developers/tumblbug-clone-coding#8]
## Tasks
- [x] EC2 인스턴스 제작
- [x] 톰캣 및 자바 설치
- [x] 탄력적 IP 할당

## Related Issues
- 해당 사항 없음

## Time line
04.23 ~ 04.26
