### ISSUE TITLE
#99 - Project update 관련 로직 구현

### ISSUE THREAD

**Issue by zangsu** [Start-as-Web-Developers/tumblbug-clone-coding#99]
## Tasks
- [x] Entity 생성 및 매핑
- [x] Repository 구현, 테스트
- [x] Service 구현, 테스트
- [x] Controller 구현, 테스트

## Related Issues
- 해당 사항 없음

## Time line
일정 조율 후 재지정
